{{- if or (eq .Values.secretBackend.type "ssm") (eq .Values.secretBackend.type "secretsmanager") }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "postgres-platform.secretStoreName" . }}
  labels:
    {{- include "postgres-platform.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      {{- if eq .Values.secretBackend.type "ssm" }}
      service: ParameterStore
      region: {{ .Values.secretBackend.ssm.region }}
      {{- else }}
      service: SecretsManager
      region: {{ .Values.secretBackend.secretsManager.region }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "postgres-platform.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
{{- end }}
