{{- if and .Values.serviceAccount.create (ne .Values.secretBackend.type "none") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-platform.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
