{{- if .Values.externalSecret.enabled }}
{{- range $name, $cfg := .Values.externalSecret.stores }}
{{- if $cfg.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" (include "nucleus.fullname" $) $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nucleus.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ printf "%s-%s" (include "nucleus.fullname" $) $name }}
    kind: SecretStore
  target:
    name: {{ printf "%s-%s" (include "nucleus.fullname" $) $name }}
    creationPolicy: Owner
  data:
    {{- range $cfg.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        {{- if eq $cfg.type "ParameterStore" }}
        key: {{ printf "%s/%s" $cfg.path .property }}
        {{- else }}
        key: {{ $cfg.path }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
