{{- if .Values.externalSecret.enabled }}
{{- range $name, $cfg := .Values.externalSecret.stores }}
{{- if $cfg.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ printf "%s-%s" (include "nucleus.fullname" $) $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nucleus.labels" $ | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ $cfg.type }}
      region: {{ $cfg.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "nucleus.serviceAccountName" $ }}
{{- end }}
{{- end }}
{{- end }}
